### PR TITLE
tokenBridge: fromIdentifier amount scaling fix

### LINKED ISSUE #580: error scaleAmount
I am getting Error: scaleAmount

### PR DESCRIPTION
**Pull request by kev1n-peters**
We were not scaling the transfer amount on the VAA to the source chain amount correctly.

Fixes #580

### CODE REVIEW

File: connect/src/protocols/tokenBridge/tokenTransfer.ts [hunk 1]
```diff
@@ -167,9 +173,20 @@ export class TokenTransfer<N extends Network = Network>
...
+      const fromChain = await wh.getChain(from.chain);
+      const tb = await fromChain.getTokenBridge();
+      const wrapped = await tb.getWrappedAsset(token);
+      nativeAddress = toNative(token.chain, wrapped.toString());
+    }
+
+    const decimals = await wh.getDecimals(from.chain, nativeAddress);
     const scaledAmount = amount.scale(
-      amount.fromBaseUnits(token.amount, TokenTransfer.MAX_DECIMALS),
-      await wh.getDecimals(token.chain, token.address),
```
Comment (kev1n-peters) [inline connect/src/protocols/tokenBridge/tokenTransfer.ts:172]: Previously we were scaling by the token origin chain's decimals, but we should scale by the source chain's decimals which may be different (e.g., Wormhole-wrapped WETH on Solana has 8 decimals vs 18 decimals on Ethereum).

**Review by artursapek — DISMISSED** [review]

**Review by artursapek — APPROVED** [review]
